layout_spectrum: 0.7340425
favicon: null
name: vikstroem
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.8425532
  lightness: 0.7212766
  saturation: 0.147315
  rhythmicContrast: 0.9001972
  brandColors:
    - '#AC390C'
    - '#FFFFFF'
    - '#300503'
    - '#FFCF5C'
    - '#D88030'
typography_spectrum: 0.3042553
